INSERT INTO teams
    (location, mascot, abbreviation, league, division)
VALUES
    ("Pittsburgh", "Pirates", "PIT", "NL", "Central"),
    ("Texas", "Rangers", "TEX", "AL", "West"),
    ("Kansas City", "Royals", "KC", "AL", "Central"),
    ("Colorado", "Rockies", "COL", "NL", "West"),
    ("St. Louis", "Cardinals", "STL", "NL", "Central"),
    ("Minnesota", "Twins", "MIN", "AL", "Central"),
    ("Chicago", "Cubs", "CHC", "NL", "Central"),
    ("Tampa Bay", "Rays", "TB", "AL", "East"),
    ("Seattle", "Mariners", "SEA", "AL", "West"),
    ("Boston", "Red Sox", "BOS", "AL", "East"),
    ("Oakland", "Athletics", "OAK", "AL", "West"),
    ("Milwaukee", "Brewers", "MIL", "NL", "Central"),
    ("Miami", "Marlins", "MIA", "NL", "East"),
    ("Cleveland", "Indians", "CLE", "AL", "Central"),
    ("San Francisco", "Giants", "SF", "NL", "West"),
    ("Toronto", "Blue Jays", "TOR", "AL", "East"),
    ("Los Angeles", "Angels", "LAA", "AL", "West"),
    ("Atlanta", "Braves", "ATL", "NL", "East"),
    ("Washington", "Nationals", "WSH", "NL", "East"),
    ("Houston", "Astros", "HOU", "AL", "West"),
    ("New York", "Mets", "NYM", "NL", "East"),
    ("Cincinnati", "Reds", "CIN", "NL", "Central"),
    ("Detroit", "Tigers", "DET", "AL", "Central"),
    ("Baltimore", "Orioles", "BAL", "AL", "East"),
    ("Pittsburgh", "Pirates", "PIT", "NL", "Central"),
    ("Texas", "Rangers", "TEX", "AL", "West");

INSERT INTO games
(startTime, homeTeamId, awayTeamId, homeScore)
VALUES
("2019-06-06 12:35:00", (SELECT id FROM teams WHERE abbreviation ="PIT"), (SELECT id FROM teams WHERE abbreviation ="ATL"), "6", "1"),  
("2019-06-06 20:05:00", (SELECT id FROM teams WHERE abbreviation ="TEX"), (SELECT id FROM teams WHERE abbreviation ="BAL"), "4", "3"),
("2019-06-06 13:15:00", (SELECT id FROM teams WHERE abbreviation ="KC"),  (SELECT id FROM teams WHERE abbreviation ="OS"), "5", "7"),
("2019-06-06 14:20:00", (SELECT id FROM teams WHERE abbreviation ="CHC"), (SELECT id FROM teams WHERE abbreviation ="COL"), "1", "3"),
("2019-06-06 13:15:00", (SELECT id FROM teams WHERE abbreviation ="STL"), (SELECT id FROM teams WHERE abbreviation ="CIN"), "3", "1"),
("2019-06-06 19:00:00", (SELECT id FROM teams WHERE abbreviation ="CLE"), (SELECT id FROM teams WHERE abbreviation ="MIN"), "4", "5"),
("2019-06-06 13:10:00", (SELECT id FROM teams WHERE abbreviation ="DET"), (SELECT id FROM teams WHERE abbreviation ="TB"), "1", "6"),
("2019-06-06 15:40:00", (SELECT id FROM teams WHERE abbreviation ="SEA"), (SELECT id FROM teams WHERE abbreviation ="HOU"), "7", "8"),
("2019-06-06 22:07:00", (SELECT id FROM teams WHERE abbreviation ="LAA"), (SELECT id FROM teams WHERE abbreviation ="OAK"), "4", "7"),
("2019-06-06 14:10:00", (SELECT id FROM teams WHERE abbreviation ="MIL"), (SELECT id FROM teams WHERE abbreviation ="MIA"), "5", "1"),
("2019-06-06 12:10:00", (SELECT id FROM teams WHERE abbreviation ="NYM"), (SELECT id FROM teams WHERE abbreviation ="SF"), "7", "3"),
("2019-06-06 19:00:00", (SELECT id FROM teams WHERE abbreviation ="TOR"), (SELECT id FROM teams WHERE abbreviation ="NYY"), "2", "6"),
("2019-06-06 22:10:00", (SELECT id FROM teams WHERE abbreviation ="SD"), (SELECT id FROM teams WHERE abbreviation ="SH"), "5","4");

INSERT INTO players
(firstName, lastName, throws, position, hits, currentTeamId)
VALUES
("Chris","Archer","R","SP","R", (SELECT id FROM teams WHERE abbreviation = "PIT")),       
("Josh","Bell","R","1B","B", (SELECT id FROM teams WHERE abbreviation = "PIT")),
("Francisco","Liriano","L","SP","L", (SELECT id FROM teams WHERE abbreviation = "PIT")),
("Starling","Marte","R","CF","R", (SELECT id FROM teams WHERE abbreviation = "PIT")),
("Colin","Moran","R","3B","L", (SELECT id FROM teams WHERE abbreviation = "PIT")),
("Kevin","Newman","R","SS","R", (SELECT id FROM teams WHERE abbreviation = "PIT")),
("Gregory","Polanco","L","RF","L", (SELECT id FROM teams WHERE abbreviation = "PIT")),
("Bryan","Reynolds","R","LF","B", (SELECT id FROM teams WHERE abbreviation = "PIT")),
("Jacob","Stallings","R","C","R",( SELECT id FROM teams WHERE abbreviation = "PIT")),
("Cole","Tucker","R","SS","B", (SELECT id FROM teams WHERE abbreviation = "PIT")),
("Felipe","Vazquez","L","RP","L", (SELECT id FROM teams WHERE abbreviation = "PIT")),
("Elvis","Andrus","R","SS","R", (SELECT id FROM teams WHERE abbreviation = "TEX")),
("Asdrubal","Cabrera","R","3B","B", (SELECT id FROM teams WHERE abbreviation = "TEX")),
("Jesse","Chavez","R","RP","R", (SELECT id FROM teams WHERE abbreviation = "TEX")),
("Delino","DeShields","R","LF","R", (SELECT id FROM teams WHERE abbreviation = "TEX")),
("Ronald","Guzman","L","1B","L", (SELECT id FROM teams WHERE abbreviation = "TEX")),
("Ariel","Jurado","R","RP","R", (SELECT id FROM teams WHERE abbreviation = "TEX")),
("Shawn","Kelley","R","RP","R", (SELECT id FROM teams WHERE abbreviation = "TEX")),
("Isiah","Kiner-Falefa","R","C","R ",(SELECT id FROM teams WHERE abbreviation = "TEX")),
("Chris","Martin","R","RP","R", (SELECT id FROM teams WHERE abbreviation = "TEX")),
("Nomar","Mazara","L","RF","L", (SELECT id FROM teams WHERE abbreviation = "TEX")),
("Rougned","Odor","R","2B","L", (SELECT id FROM teams WHERE abbreviation = "TEX")),
("Hunter","Pence","R","RF","R", (SELECT id FROM teams WHERE abbreviation = "TEX")),
("Danny","Santana","R","CF","B", (SELECT id FROM teams WHERE abbreviation = "TEX")),
("Scott","Barlow","R","RP","R", (SELECT id FROM teams WHERE abbreviation = "KC")),
("Cheslor","Cuthbert","R","3B","R", (SELECT id FROM teams WHERE abbreviation = "KC")),
("Danny","Duffy","L","SP","L", (SELECT id FROM teams WHERE abbreviation = "KC")),
("Brian","Flynn","L","RP","L", (SELECT id FROM teams WHERE abbreviation = "KC")),
("Cam","Gallagher","R","C","R",( SELECT id FROM teams WHERE abbreviation = "KC")),
("Alex","Gordon","R","LF","L", (SELECT id FROM teams WHERE abbreviation = "KC")),
("Billy","Hamilton","R","CF","B", (SELECT id FROM teams WHERE abbreviation = "KC")),
("Nicky","Lopez","R","2B","L", (SELECT id FROM teams WHERE abbreviation = "KC")),
("Kevin","McCarthy","R","RP","R", (SELECT id FROM teams WHERE abbreviation = "KC")),
("Whit","Merrifield","R","2B","R", (SELECT id FROM teams WHERE abbreviation = "KC")),
("Adalberto","Mondesi","R","2B","B", (SELECT id FROM teams WHERE abbreviation = "KC")),
("Ryan","O'Hearn","L","1B"," L",(SELECT id FROM teams WHERE abbreviation = "KC")),
("Jorge","Soler","R","RF","R", (SELECT id FROM teams WHERE abbreviation = "KC")),
("Nolan","Arenado","R","3B","R", (SELECT id FROM teams WHERE abbreviation = "COL")),
("David","Dahl","R","LF","L", (SELECT id FROM teams WHERE abbreviation = "COL")),
("Ian","Desmond","R","1B","R", (SELECT id FROM teams WHERE abbreviation = "COL")),
("Jairo","Diaz","R","RP","R", (SELECT id FROM teams WHERE abbreviation = "COL")),
("Chris","Iannetta","R","C","R",( SELECT id FROM teams WHERE abbreviation = "COL")),
("Peter","Lambert","R","SP","R", (SELECT id FROM teams WHERE abbreviation = "COL")),
("Scott","Oberg","R","RP","R", (SELECT id FROM teams WHERE abbreviation = "COL")),
("Mark","Reynolds","R","1B","R", (SELECT id FROM teams WHERE abbreviation = "COL")),
("Brendan","Rodgers","R","SS","R", (SELECT id FROM teams WHERE abbreviation = "COL")),
("Trevor","Story","R","SS","R", (SELECT id FROM teams WHERE abbreviation = "COL")),
("Raimel","Tapia","L","CF","L", (SELECT id FROM teams WHERE abbreviation = "COL")),
("Harrison","Bader","R","CF","R", (SELECT id FROM teams WHERE abbreviation = "STL")),
("Matt","Carpenter","R","1B","L", (SELECT id FROM teams WHERE abbreviation = "STL")),
("Paul","DeJong","R","SS","R", (SELECT id FROM teams WHERE abbreviation = "STL")),
("Dexter","Fowler","R","RF","B", (SELECT id FROM teams WHERE abbreviation = "STL")),
("John","Gant","R","RP","R", (SELECT id FROM teams WHERE abbreviation = "STL")),
("Paul","Goldschmidt","R","1B","R", (SELECT id FROM teams WHERE abbreviation = "STL")),
("Jordan","Hicks","R","RP","R", (SELECT id FROM teams WHERE abbreviation = "STL")),
("Dakota","Hudson","R","SP","R", (SELECT id FROM teams WHERE abbreviation = "STL")),
("Andrew","Miller","L","RP","L", (SELECT id FROM teams WHERE abbreviation = "STL")),
("Marcell","Ozuna","R","LF","R", (SELECT id FROM teams WHERE abbreviation = "STL")),
("Matt","Wieters","R","C","B",( SELECT id FROM teams WHERE abbreviation = "STL")),
("Kolten","Wong","R","2B","L", (SELECT id FROM teams WHERE abbreviation = "STL")),
("Ehire","Adrianza","R","SS","B", (SELECT id FROM teams WHERE abbreviation = "MIN")),
("Willians","Astudillo","R","C","R",( SELECT id FROM teams WHERE abbreviation = "MIN")),
("Jose","Berrios","R","SP","R", (SELECT id FROM teams WHERE abbreviation = "MIN")),
("C.J.","Cron","R","1B"," R",(SELECT id FROM teams WHERE abbreviation = "MIN")),
("Mitch","Garver","R","C","R",( SELECT id FROM teams WHERE abbreviation = "MIN")),
("Marwin","Gonzalez","R","3B","B", (SELECT id FROM teams WHERE abbreviation = "MIN")),
("Max","Kepler","L","RF","L", (SELECT id FROM teams WHERE abbreviation = "MIN")),
("Matt","Magill","R","RP","R", (SELECT id FROM teams WHERE abbreviation = "MIN")),
("Trevor","May","R","RP","R", (SELECT id FROM teams WHERE abbreviation = "MIN")),
("Jorge","Polanco","R","SS","B", (SELECT id FROM teams WHERE abbreviation = "MIN")),
("Taylor","Rogers","L","RP","L", (SELECT id FROM teams WHERE abbreviation = "MIN")),
("Eddie","Rosario","R","LF","L", (SELECT id FROM teams WHERE abbreviation = "MIN")),
("Jonathan","Schoop","R","2B","R", (SELECT id FROM teams WHERE abbreviation = "MIN")),
("Albert","Almora Jr.","R","CF", "R",(SELECT id FROM teams WHERE abbreviation = "CHC")),
("Javier","Baez","R","SS","R", (SELECT id FROM teams WHERE abbreviation = "CHC")),
("David","Bote","R","3B","R", (SELECT id FROM teams WHERE abbreviation = "CHC")),
("Kris","Bryant","R","3B","R", (SELECT id FROM teams WHERE abbreviation = "CHC")),
("Willson","Contreras","R","C","R",( SELECT id FROM teams WHERE abbreviation = "CHC")),
("Daniel","Descalso","R","3B","L", (SELECT id FROM teams WHERE abbreviation = "CHC")),
("Carl","Edwards Jr.","R","RP", "R",(SELECT id FROM teams WHERE abbreviation = "CHC")),
("Jose","Quintana","L","SP","R", (SELECT id FROM teams WHERE abbreviation = "CHC")),
("Anthony","Rizzo","L","1B","L", (SELECT id FROM teams WHERE abbreviation = "CHC")),
("Kyle","Ryan","L","SP","L", (SELECT id FROM teams WHERE abbreviation = "CHC")),
("Kyle","Schwarber","R","LF","L", (SELECT id FROM teams WHERE abbreviation = "CHC")),
("Willy","Adames","R","SS","R", (SELECT id FROM teams WHERE abbreviation = "TB")),
("Christian","Arroyo","R","3B","R", (SELECT id FROM teams WHERE abbreviation = "TB")),
("Jalen","Beeks","L","RP","L", (SELECT id FROM teams WHERE abbreviation = "TB")),
("Diego","Castillo","R","RP","R", (SELECT id FROM teams WHERE abbreviation = "TB")),
("Travis","d'Arnaud","R","C","R ",(SELECT id FROM teams WHERE abbreviation = "TB")),
("Yandy","Diaz","R","3B","R", (SELECT id FROM teams WHERE abbreviation = "TB")),
("Avisail","Garcia","R","RF","R", (SELECT id FROM teams WHERE abbreviation = "TB")),
("Kevin","Kiermaier","R","CF","L", (SELECT id FROM teams WHERE abbreviation = "TB")),
("Austin","Meadows","L","CF","L", (SELECT id FROM teams WHERE abbreviation = "TB")),
("Tommy","Pham","R","CF","R", (SELECT id FROM teams WHERE abbreviation = "TB")),
("Daniel","Robertson","R","2B","R", (SELECT id FROM teams WHERE abbreviation = "TB")),
("Chaz","Roe","R","RP","R", (SELECT id FROM teams WHERE abbreviation = "TB")),
("Ryne","Stanek","R","RP","R", (SELECT id FROM teams WHERE abbreviation = "TB")),
("Hunter","Wood","R","RP","R", (SELECT id FROM teams WHERE abbreviation = "TB")),
("Austin","Adams","R","RP","R", (SELECT id FROM teams WHERE abbreviation = "SEA")),
("Anthony","Bass","R","RP","R", (SELECT id FROM teams WHERE abbreviation = "SEA")),
("Gerson","Bautista","R","RP","R", (SELECT id FROM teams WHERE abbreviation = "SEA")),
("Brandon","Brennan","R","RP","R", (SELECT id FROM teams WHERE abbreviation = "SEA")),
("Roenis","Elias","L","SP","L", (SELECT id FROM teams WHERE abbreviation = "SEA")),
("Edwin","Encarnacion","R","DH","R", (SELECT id FROM teams WHERE abbreviation = "SEA")),
("Matt","Festa","R","RP","R", (SELECT id FROM teams WHERE abbreviation = "SEA")),
("Cory","Gearrin","R","RP","R", (SELECT id FROM teams WHERE abbreviation = "SEA")),
("Mitch","Haniger","R","RF","R", (SELECT id FROM teams WHERE abbreviation = "SEA")),
("Shed","Long","R","2B","L", (SELECT id FROM teams WHERE abbreviation = "SEA")),
("Tommy","Milone","L","SP","L", (SELECT id FROM teams WHERE abbreviation = "SEA")),
("Dylan","Moore","R","3B","R", (SELECT id FROM teams WHERE abbreviation = "SEA")),
("Omar","Narvaez","R","C","L",( SELECT id FROM teams WHERE abbreviation = "SEA")),
("Domingo","Santana","R","RF","R", (SELECT id FROM teams WHERE abbreviation = "SEA")),
("Kyle","Seager","R","3B","L", (SELECT id FROM teams WHERE abbreviation = "SEA")),
("Mallex","Smith","R","CF","L", (SELECT id FROM teams WHERE abbreviation = "SEA")),
("Daniel","Vogelbach","R","1B","L", (SELECT id FROM teams WHERE abbreviation = "SEA")),
("Matt","Barnes","R","RP","R", (SELECT id FROM teams WHERE abbreviation = "BOS")),
("Andrew","Benintendi","L","LF","L", (SELECT id FROM teams WHERE abbreviation = "BOS")),
("Mookie","Betts","R","RF","R", (SELECT id FROM teams WHERE abbreviation = "BOS")),
("Xander","Bogaerts","R","SS","R", (SELECT id FROM teams WHERE abbreviation = "BOS")),
("Jackie","Bradley Jr.","R","CF", "L",(SELECT id FROM teams WHERE abbreviation = "BOS")),
("Ryan","Brasier","R","RP","R", (SELECT id FROM teams WHERE abbreviation = "BOS")),
("Colten","Brewer","R","RP","R", (SELECT id FROM teams WHERE abbreviation = "BOS")),
("Michael","Chavis","R","3B","R", (SELECT id FROM teams WHERE abbreviation = "BOS")),
("Rafael","Devers","R","3B","L", (SELECT id FROM teams WHERE abbreviation = "BOS")),
("Heath","Hembree","R","RP","R", (SELECT id FROM teams WHERE abbreviation = "BOS")),
("J.D.","Martinez","R","LF"," R",(SELECT id FROM teams WHERE abbreviation = "BOS")),
("Eduardo","Nunez","R","2B","R", (SELECT id FROM teams WHERE abbreviation = "BOS")),
("Josh","Taylor","L","RP","L", (SELECT id FROM teams WHERE abbreviation = "BOS")),
("Christian","Vazquez","R","C","R",( SELECT id FROM teams WHERE abbreviation = "BOS")),
("Marcus","Walden","R","RP","R", (SELECT id FROM teams WHERE abbreviation = "BOS")),
("Ryan","Weber","R","RP","R", (SELECT id FROM teams WHERE abbreviation = "BOS")),
("Ryan","Buchter","L","RP","L", (SELECT id FROM teams WHERE abbreviation = "OAK")),
("Mark","Canha","R","1B","R", (SELECT id FROM teams WHERE abbreviation = "OAK")),
("Matt","Chapman","R","3B","R", (SELECT id FROM teams WHERE abbreviation = "OAK")),
("Khris","Davis","R","LF","R", (SELECT id FROM teams WHERE abbreviation = "OAK")),
("Mike","Fiers","R","SP","R", (SELECT id FROM teams WHERE abbreviation = "OAK")),
("Liam","Hendriks","R","RP","R", (SELECT id FROM teams WHERE abbreviation = "OAK")),
("Ramon","Laureano","R","CF","R", (SELECT id FROM teams WHERE abbreviation = "OAK")),
("Josh","Phegley","R","C","R",( SELECT id FROM teams WHERE abbreviation = "OAK")),
("Chad","Pinder","R","SS","R", (SELECT id FROM teams WHERE abbreviation = "OAK")),
("Stephen","Piscotty","R","RF","R", (SELECT id FROM teams WHERE abbreviation = "OAK")),
("Jurickson","Profar","R","SS","B", (SELECT id FROM teams WHERE abbreviation = "OAK")),
("Marcus","Semien","R","SS","R", (SELECT id FROM teams WHERE abbreviation = "OAK")),
("Joakim","Soria","R","RP","R", (SELECT id FROM teams WHERE abbreviation = "OAK")),
("Lou","Trivino","R","RP","R", (SELECT id FROM teams WHERE abbreviation = "OAK")),
("Jesus","Aguilar","R","1B","R", (SELECT id FROM teams WHERE abbreviation = "MIL")),
("Orlando","Arcia","R","SS","R", (SELECT id FROM teams WHERE abbreviation = "MIL")),
("Ryan","Braun","R","LF","R", (SELECT id FROM teams WHERE abbreviation = "MIL")),
("Lorenzo","Cain","R","CF","R", (SELECT id FROM teams WHERE abbreviation = "MIL")),
("Josh","Hader","L","RP","L", (SELECT id FROM teams WHERE abbreviation = "MIL")),
("Jeremy","Jeffress","R","RP","R", (SELECT id FROM teams WHERE abbreviation = "MIL")),
("Mike","Moustakas","R","2B","L", (SELECT id FROM teams WHERE abbreviation = "MIL")),
("Freddy","Peralta","R","SP","R", (SELECT id FROM teams WHERE abbreviation = "MIL")),
("Hernan","Perez","R","3B","R", (SELECT id FROM teams WHERE abbreviation = "MIL")),
("Manny","Pina","R","C","R",( SELECT id FROM teams WHERE abbreviation = "MIL")),
("Christian","Yelich","R","RF","L", (SELECT id FROM teams WHERE abbreviation = "MIL")),
("Jorge","Alfaro","R","C","R",( SELECT id FROM teams WHERE abbreviation = "MIA")),
("Brian","Anderson","R","3B","R", (SELECT id FROM teams WHERE abbreviation = "MIA")),
("Austin","Brice","R","RP","R", (SELECT id FROM teams WHERE abbreviation = "MIA")),
("Starlin","Castro","R","2B","R", (SELECT id FROM teams WHERE abbreviation = "MIA")),
("Garrett","Cooper","R","LF","R", (SELECT id FROM teams WHERE abbreviation = "MIA")),
("Austin","Dean","R","LF","R", (SELECT id FROM teams WHERE abbreviation = "MIA")),
("Tayron","Guerrero","R","RP","R", (SELECT id FROM teams WHERE abbreviation = "MIA")),
("Harold","Ramirez","R","RF","R", (SELECT id FROM teams WHERE abbreviation = "MIA")),
("JT","Riddle","R","SS","L", (SELECT id FROM teams WHERE abbreviation = "MIA")),
("Miguel","Rojas","R","SS","R", (SELECT id FROM teams WHERE abbreviation = "MIA")),
("Sergio","Romo","R","SP","R", (SELECT id FROM teams WHERE abbreviation = "MIA")),
("Caleb","Smith","L","SP","R", (SELECT id FROM teams WHERE abbreviation = "MIA")),
("Trevor","Bauer","R","SP","R", (SELECT id FROM teams WHERE abbreviation = "CLE")),
("Jake","Bauers","L","LF","L", (SELECT id FROM teams WHERE abbreviation = "CLE")),
("Jon","Edwards","R","RP","R", (SELECT id FROM teams WHERE abbreviation = "CLE")),
("Jason","Kipnis","R","2B","L", (SELECT id FROM teams WHERE abbreviation = "CLE")),
("Francisco","Lindor","R","SS","B", (SELECT id FROM teams WHERE abbreviation = "CLE")),
("Jordan","Luplow","R","RF","R", (SELECT id FROM teams WHERE abbreviation = "CLE")),
("Leonys","Martin","R","CF","L", (SELECT id FROM teams WHERE abbreviation = "CLE")),
("Tyler","Naquin","R","CF","L", (SELECT id FROM teams WHERE abbreviation = "CLE")),
("Roberto","Perez","R","C","R",( SELECT id FROM teams WHERE abbreviation = "CLE")),
("Jose","Ramirez","R","2B","B", (SELECT id FROM teams WHERE abbreviation = "CLE")),
("Carlos","Santana","R","1B","B", (SELECT id FROM teams WHERE abbreviation = "CLE")),
("Josh","Smith","L","RP","L", (SELECT id FROM teams WHERE abbreviation = "CLE")),
("Shaun","Anderson","R","SP","R", (SELECT id FROM teams WHERE abbreviation = "SF")),
("Brandon","Belt","L","1B","L", (SELECT id FROM teams WHERE abbreviation = "SF")),
("Brandon","Crawford","R","SS","L", (SELECT id FROM teams WHERE abbreviation = "SF")),
("Steven","Duggar","R","CF","L", (SELECT id FROM teams WHERE abbreviation = "SF")),
("Mark","Melancon","R","RP","R", (SELECT id FROM teams WHERE abbreviation = "SF")),
("Reyes","Moronta","R","RP","R", (SELECT id FROM teams WHERE abbreviation = "SF")),
("Joe","Panik","R","2B","L", (SELECT id FROM teams WHERE abbreviation = "SF")),
("Kevin","Pillar","R","CF","R", (SELECT id FROM teams WHERE abbreviation = "SF")),
("Pablo","Sandoval","R","3B","B", (SELECT id FROM teams WHERE abbreviation = "SF")),
("Stephen","Vogt","R","C","L",( SELECT id FROM teams WHERE abbreviation = "SF")),
("Tony","Watson","L","RP","L", (SELECT id FROM teams WHERE abbreviation = "SF")),
("Mike","Yastrzemski","L","LF","L", (SELECT id FROM teams WHERE abbreviation = "SF")),
("Brandon","Drury","R","3B","R", (SELECT id FROM teams WHERE abbreviation = "TOR")),
("Freddy","Galvis","R","SS","B", (SELECT id FROM teams WHERE abbreviation = "TOR")),
("Randal","Grichuk","R","LF","R", (SELECT id FROM teams WHERE abbreviation = "TOR")),
("Vladimir","Guerrero Jr.","R","3B", "R",(SELECT id FROM teams WHERE abbreviation = "TOR")),
("Lourdes","Gurriel Jr.","R","2B", "R",(SELECT id FROM teams WHERE abbreviation = "TOR")),
("Teoscar","Hernandez","R","RF","R", (SELECT id FROM teams WHERE abbreviation = "TOR")),
("Edwin","Jackson","R","SP","R", (SELECT id FROM teams WHERE abbreviation = "TOR")),
("Elvis","Luciano","R","RP","R", (SELECT id FROM teams WHERE abbreviation = "TOR")),
("Luke","Maile","R","C","R",( SELECT id FROM teams WHERE abbreviation = "TOR")),
("Tim","Mayza","L","RP","L", (SELECT id FROM teams WHERE abbreviation = "TOR")),
("Thomas","Pannone","L","RP","L", (SELECT id FROM teams WHERE abbreviation = "TOR")),
("Justin","Smoak","L","1B","B", (SELECT id FROM teams WHERE abbreviation = "TOR")),
("Eric","Sogard","R","2B","L", (SELECT id FROM teams WHERE abbreviation = "TOR")),
("Jaime","Barria","R","SP","R", (SELECT id FROM teams WHERE abbreviation = "LAA")),
("Kole","Calhoun","L","RF","L", (SELECT id FROM teams WHERE abbreviation = "LAA")),
("David","Fletcher","R","SS","R", (SELECT id FROM teams WHERE abbreviation = "LAA")),
("Dustin","Garneau","R","C","R",( SELECT id FROM teams WHERE abbreviation = "LAA")),
("Brian","Goodwin","R","CF","L", (SELECT id FROM teams WHERE abbreviation = "LAA")),
("Tommy","La Stella","R","3B"," L",(SELECT id FROM teams WHERE abbreviation = "LAA")),
("Shohei","Ohtani","R","DH","L", (SELECT id FROM teams WHERE abbreviation = "LAA")),
("Luis","Rengifo","R","2B","B", (SELECT id FROM teams WHERE abbreviation = "LAA")),
("Tyler","Skaggs","L","SP","L", (SELECT id FROM teams WHERE abbreviation = "LAA")),
("Mike","Trout","R","CF","R", (SELECT id FROM teams WHERE abbreviation = "LAA")),
("Jared","Walsh","L","1B","L", (SELECT id FROM teams WHERE abbreviation = "LAA")),
("Ronald","Acuna Jr.","R","LF", "R",(SELECT id FROM teams WHERE abbreviation = "ATL")),
("Ozzie","Albies","R","2B","B", (SELECT id FROM teams WHERE abbreviation = "ATL")),
("Josh","Donaldson","R","3B","R", (SELECT id FROM teams WHERE abbreviation = "ATL")),
("Mike","Foltynewicz","R","SP","R", (SELECT id FROM teams WHERE abbreviation = "ATL")),
("Freddie","Freeman","R","1B","L", (SELECT id FROM teams WHERE abbreviation = "ATL")),
("Nick","Markakis","L","RF","L", (SELECT id FROM teams WHERE abbreviation = "ATL")),
("Brian","McCann","R","C","L",( SELECT id FROM teams WHERE abbreviation = "ATL")),
("Sean","Newcomb","L","SP","L", (SELECT id FROM teams WHERE abbreviation = "ATL")),
("Austin","Riley","R","3B","R", (SELECT id FROM teams WHERE abbreviation = "ATL")),
("Dansby","Swanson","R","SS","R", (SELECT id FROM teams WHERE abbreviation = "ATL")),
("Jacob","Webb","R","RP","R", (SELECT id FROM teams WHERE abbreviation = "ATL")),
("Patrick","Corbin","L","SP","L", (SELECT id FROM teams WHERE abbreviation = "WSH")),
("Brian","Dozier","R","2B","R", (SELECT id FROM teams WHERE abbreviation = "WSH")),
("Yan","Gomes","R","C","R",( SELECT id FROM teams WHERE abbreviation = "WSH")),
("Matt","Grace","L","RP","L", (SELECT id FROM teams WHERE abbreviation = "WSH")),
("Javy","Guerra","R","RP","R", (SELECT id FROM teams WHERE abbreviation = "WSH")),
("Howie","Kendrick","R","2B","R", (SELECT id FROM teams WHERE abbreviation = "WSH")),
("Anthony","Rendon","R","3B","R", (SELECT id FROM teams WHERE abbreviation = "WSH")),
("Victor","Robles","R","CF","R", (SELECT id FROM teams WHERE abbreviation = "WSH")),
("Tony","Sipp","L","RP","L", (SELECT id FROM teams WHERE abbreviation = "WSH")),
("Juan","Soto","L","LF","L", (SELECT id FROM teams WHERE abbreviation = "WSH")),
("Michael","Taylor","R","CF","R", (SELECT id FROM teams WHERE abbreviation = "WSH")),
("Trea","Turner","R","SS","R", (SELECT id FROM teams WHERE abbreviation = "WSH")),
("Michael","Brantley","L","LF","L", (SELECT id FROM teams WHERE abbreviation = "HOU")),
("Alex","Bregman","R","3B","R", (SELECT id FROM teams WHERE abbreviation = "HOU")),
("Robinson","Chirinos","R","C","R",( SELECT id FROM teams WHERE abbreviation = "HOU")),
("Chris","Devenski","R","RP","R", (SELECT id FROM teams WHERE abbreviation = "HOU")),
("Derek","Fisher","R","CF","L", (SELECT id FROM teams WHERE abbreviation = "HOU")),
("Yuli","Gurriel","R","1B","R", (SELECT id FROM teams WHERE abbreviation = "HOU")),
("Will","Harris","R","RP","R", (SELECT id FROM teams WHERE abbreviation = "HOU")),
("Josh","James","R","SP","R", (SELECT id FROM teams WHERE abbreviation = "HOU")),
("Tony","Kemp","R","LF","L", (SELECT id FROM teams WHERE abbreviation = "HOU")),
("Jake","Marisnick","R","CF","R", (SELECT id FROM teams WHERE abbreviation = "HOU")),
("Jack","Mayfield","R","2B","R", (SELECT id FROM teams WHERE abbreviation = "HOU")),
("Roberto","Osuna","R","RP","R", (SELECT id FROM teams WHERE abbreviation = "HOU")),
("Ryan","Pressly","R","RP","R", (SELECT id FROM teams WHERE abbreviation = "HOU")),
("Hector","Rondon","R","RP","R", (SELECT id FROM teams WHERE abbreviation = "HOU")),
("Justin","Verlander","R","SP","R", (SELECT id FROM teams WHERE abbreviation = "HOU")),
("Tyler","White","R","2B","R", (SELECT id FROM teams WHERE abbreviation = "HOU")),
("Pete","Alonso","R","1B","R", (SELECT id FROM teams WHERE abbreviation = "NYM")),
("Michael","Conforto","R","RF","L", (SELECT id FROM teams WHERE abbreviation = "NYM")),
("Jeurys","Familia","R","RP","R", (SELECT id FROM teams WHERE abbreviation = "NYM")),
("Todd","Frazier","R","3B","R", (SELECT id FROM teams WHERE abbreviation = "NYM")),
("Adeiny","Hechavarria","R","SS","R", (SELECT id FROM teams WHERE abbreviation = "NYM")),
("Juan","Lagares","R","CF","R", (SELECT id FROM teams WHERE abbreviation = "NYM")),
("Seth","Lugo","R","SP","R", (SELECT id FROM teams WHERE abbreviation = "NYM")),
("Tomas","Nido","R","C","R",( SELECT id FROM teams WHERE abbreviation = "NYM")),
("Amed","Rosario","R","SS","R", (SELECT id FROM teams WHERE abbreviation = "NYM")),
("Dominic","Smith","L","1B","L", (SELECT id FROM teams WHERE abbreviation = "NYM")),
("Zack","Wheeler","R","SP","L", (SELECT id FROM teams WHERE abbreviation = "NYM")),
("Tucker","Barnhart","R","C","B",( SELECT id FROM teams WHERE abbreviation = "CIN")),
("Anthony","DeSclafani","R","SP","R", (SELECT id FROM teams WHERE abbreviation = "CIN")),
("Derek","Dietrich","R","LF","L", (SELECT id FROM teams WHERE abbreviation = "CIN")),
("Amir","Garrett","L","RP","R", (SELECT id FROM teams WHERE abbreviation = "CIN")),
("Jose","Iglesias","R","SS","R", (SELECT id FROM teams WHERE abbreviation = "CIN")),
("Michael","Lorenzen","R","RP","R", (SELECT id FROM teams WHERE abbreviation = "CIN")),
("Wandy","Peralta","L","RP","L", (SELECT id FROM teams WHERE abbreviation = "CIN")),
("Yasiel","Puig","R","RF","R", (SELECT id FROM teams WHERE abbreviation = "CIN")),
("Nick","Senzel","R","3B","R", (SELECT id FROM teams WHERE abbreviation = "CIN")),
("Eugenio","Suarez","R","3B","R", (SELECT id FROM teams WHERE abbreviation = "CIN")),
("Joey","Votto","R","1B","L", (SELECT id FROM teams WHERE abbreviation = "CIN")),
("Jesse","Winker","L","RF","L", (SELECT id FROM teams WHERE abbreviation = "CIN")),
("Austin","Adams","R","RP","R", (SELECT id FROM teams WHERE abbreviation = "DET")),
("Victor","Alcantara","R","RP","R", (SELECT id FROM teams WHERE abbreviation = "DET")),
("Gordon","Beckham","R","3B","R", (SELECT id FROM teams WHERE abbreviation = "DET")),
("Nicholas","Castellanos","R","RF","R", (SELECT id FROM teams WHERE abbreviation = "DET")),
("Brandon","Dixon","R","LF","R", (SELECT id FROM teams WHERE abbreviation = "DET")),
("Buck","Farmer","R","RP","L", (SELECT id FROM teams WHERE abbreviation = "DET")),
("Niko","Goodrum","R","SS","B", (SELECT id FROM teams WHERE abbreviation = "DET")),
("Grayson","Greiner","R","C","R",( SELECT id FROM teams WHERE abbreviation = "DET")),
("JaCoby","Jones","R","LF","R", (SELECT id FROM teams WHERE abbreviation = "DET")),
("Dawel","Lugo","R","2B","R", (SELECT id FROM teams WHERE abbreviation = "DET")),
("Daniel","Norris","L","SP","L", (SELECT id FROM teams WHERE abbreviation = "DET")),
("Ronny","Rodriguez","R","3B","R", (SELECT id FROM teams WHERE abbreviation = "DET")),
("Christin","Stewart","R","LF","L", (SELECT id FROM teams WHERE abbreviation = "DET")),
("Daniel","Stumpf","L","RP","L", (SELECT id FROM teams WHERE abbreviation = "DET")),
("Hanser","Alberto","R","SS","R", (SELECT id FROM teams WHERE abbreviation = "BAL")),
("Miguel","Castro","R","RP","R", (SELECT id FROM teams WHERE abbreviation = "BAL")),
("Chris","Davis","R","1B","L", (SELECT id FROM teams WHERE abbreviation = "BAL")),
("David","Hess","R","RP","R", (SELECT id FROM teams WHERE abbreviation = "BAL")),
("Trey","Mancini","R","LF","R", (SELECT id FROM teams WHERE abbreviation = "BAL")),
("Richie","Martin","R","SS","R", (SELECT id FROM teams WHERE abbreviation = "BAL")),
("Renato","Nunez","R","3B","R", (SELECT id FROM teams WHERE abbreviation = "BAL")),
("Rio","Ruiz","R","3B","L", (SELECT id FROM teams WHERE abbreviation = "BAL")),
("Chance","Sisco","R","C","L",( SELECT id FROM teams WHERE abbreviation = "BAL")),
("Dwight","Smith Jr.","R","RF", "L",(SELECT id FROM teams WHERE abbreviation = "BAL")),
("Stevie","Wilkerson","R","SS","B", (SELECT id FROM teams WHERE abbreviation = "BAL")),
("Aroldis","Chapman","L","RP","L", (SELECT id FROM teams WHERE abbreviation = "NYY")),
("Thairo","Estrada","R","SS","R", (SELECT id FROM teams WHERE abbreviation = "NYY")),
("Clint","Frazier","R","LF","R", (SELECT id FROM teams WHERE abbreviation = "NYY")),
("Chad","Green","R","RP","L", (SELECT id FROM teams WHERE abbreviation = "NYY")),
("J.A.","Happ","L","SP"," L",(SELECT id FROM teams WHERE abbreviation = "NYY")),
("Aaron","Hicks","R","CF","B", (SELECT id FROM teams WHERE abbreviation = "NYY")),
("DJ","LeMahieu","R","2B","R", (SELECT id FROM teams WHERE abbreviation = "NYY")),
("Cameron","Maybin","R","LF","R", (SELECT id FROM teams WHERE abbreviation = "NYY")),
("Kendrys","Morales","R","DH","B", (SELECT id FROM teams WHERE abbreviation = "NYY")),
("Gary","Sanchez","R","C","R",( SELECT id FROM teams WHERE abbreviation = "NYY")),
("Gio","Urshela","R","3B","R", (SELECT id FROM teams WHERE abbreviation = "NYY")),
("Luke","Voit","R","1B","R", (SELECT id FROM teams WHERE abbreviation = "NYY")),
("Austin","Hedges","R","C","R",( SELECT id FROM teams WHERE abbreviation = "SD")),
("Ian","Kinsler","R","2B","R", (SELECT id FROM teams WHERE abbreviation = "SD")),
("Joey","Lucchesi","L","SP","L", (SELECT id FROM teams WHERE abbreviation = "SD")),
("Manny","Machado","R","SS","R", (SELECT id FROM teams WHERE abbreviation = "SD")),
("Manuel","Margot","R","CF","R", (SELECT id FROM teams WHERE abbreviation = "SD")),
("Wil","Myers","R","RF","R", (SELECT id FROM teams WHERE abbreviation = "SD")),
("Hunter","Renfroe","R","RF","R", (SELECT id FROM teams WHERE abbreviation = "SD")),
("Franmil","Reyes","R","CF","R", (SELECT id FROM teams WHERE abbreviation = "SD")),
("Craig","Stammen","R","RP","R", (SELECT id FROM teams WHERE abbreviation = "SD")),
("Fernando","Tatis Jr.","R","SS", "R",(SELECT id FROM teams WHERE abbreviation = "SD")),
("Trey","Wingenter","R","RP","R", (SELECT id FROM teams WHERE abbreviation = "SD")),
("Matt","Wisler","R","SP","R", (SELECT id FROM teams WHERE abbreviation = "SD")),
("Kirby","Yates","R","RP","L", (SELECT id FROM teams WHERE abbreviation = "SD"));

INSERT INTO hittingStats
(atBats, runs, hits, doules, triples, homeRuns, runsBattedIn, walks, strikeOuts, steals, playerId, gameId)